bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /fusion/odom
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"